#!/usr/bin/env zsh

fzf-man-widget() {
    manpage="gecho {} | gsed 's/\([[:alnum:][:punct:]]*\) (\([[:alnum:]]*\)).*/\2 \1/'"
    batman="${manpage} | xargs -r man | col -bx | bat --language=man --plain --color always --theme=\"Monokai Extended\""
        man -k . | gsort \
        | gawk -v cyan=$(tput setaf 6) -v blue=$(tput setaf 4) -v res=$(tput sgr0) -v bld=$(tput bold) '{ $1=cyan bld $1; $2=res blue $2; } 1' \
        | fzf \
            -q "$1" \
            --ansi \
            --tiebreak=begin \
            --prompt=' Man > ' \
            --preview-window '50%,rounded,<50(up,85%,border-bottom)' \
            --preview "${batman}" \
            --bind "enter:execute(${manpage} | gxargs -r man)" \
            --bind "alt-c:+change-preview(cht.sh {1}+change-prompt(♾ Cheat > )" \
            --bind "alt-m:+change-preview(${batman})+change-prompt( Man > )" \
            --bind "alt-t:+change-preview(tldr --color=always {1})+change-prompt( TLDR > )"
        zle reset-prompt
}
bindkey '^h' fzf-man-widget
zle -N fzf-man-widget

# vim: ft=zsh sw=4 ts=8 sts=4 tw=100 cc=+1 et ai:
