local lsp = {
  Array = ' ',
  Boolean = '󰨙 ',
  Class = '󰙅 ',
  Constant = '󰏿 ',
  Constructor = ' ',
  Enum = ' ',
  EnumMember = ' ',
  Event = ' ',
  Field = '󰜢 ',
  File = '󰈙 ',
  Folder = ' ',
  Function = '󰊕 ',
  Image = '󰈫',
  -- Interface = '󰕘 ',
  Interface = ' ',
  Keyword = '󰌋 ',
  Method = ' ',
  Module = ' ',
  Namespace = '󰌗 ',
  Null = '󰢤 ',
  Number = '󰎠 ',
  Object = '󰅩 ',
  Operator = '󰆕 ',
  Package = ' ',
  Property = ' ',
  String = '󰉾 ',
  Struct = '󱡠 ',
  TypeParameter = '󰊄 ',
  Variable = '󰀫 ',
}

local M = {
  ai = {
    sources = {
      'codecompanion',
      'copilot',
    },
  },

  icons = {
    actions = {
      close = '󰅖 ',
      close_box = '󰅗 ',
      close_hexagon = '󰅜 ',
      close_outline = '󰅚 ',
      close_round = '󰅙 ',
    },
    completion_items = {
      Class = lsp.Class,
      Color = '󰏘 ',
      Constant = lsp.Constant,
      Constructor = lsp.Constructor,
      Enum = lsp.Enum,
      EnumMember = lsp.EnumMember,
      Event = ' ',
      Field = lsp.Field,
      File = lsp.File,
      Folder = '󰉋 ',
      Function = lsp.Function,
      Interface = lsp.Interface,
      Keyword = lsp.Key,
      Method = lsp.Method,
      Module = lsp.Module,
      Operator = lsp.Operator,
      Property = lsp.Property,
      Reference = '󰋺 ',
      Snippet = '󰩫 ',
      Struct = lsp.Struct,
      Text = ' ',
      TypeParameter = lsp.TypeParameter,
      Unit = ' ',
      Value = '󰦨 ',
      Variable = lsp.Variable,
      --
      -- Extras that are not part of lsp.CompleteItemKind.
      Code = ' ',
      Copilot = ' ',
      Version = '󱘗 ', -- crates.nvim lsp completion type.
    },
    diagnostics = {
      error = '󰅚',
      warn = '󰀪',
      info = '',
      hint = '󰌶',
      debug = '',
      trace = '',
    },
    fold = {
      open = ' ',
      closed = '',
    },
    git = {
      add = '',
      added = '',
      branch = ' ',
      conflict = ' ',
      deleted = '',
      diff = ' ',
      ignore = ' ',
      ignored = ' ',
      logo = '󰊢 ',
      mod = ' ',
      modified = '󰄱', -- aka unstaged
      remove = '',
      rename = ' ',
      renamed = '',
      repo = ' ',
      staged = ' ',
      unmerged = '',
      unstaged = '󰄱 ',
      untracked = '*',
    },
    greek = {
      alpha = '󰀫',
      beta = '𝛃',
      delta = '𝛿',
      gamma = '𝛾',
      pi = '',
      phi = '𝜙',
      theta = '𝜃',
      psi = '𝜓',
      sigma = '𝜎',
      mu = '𝜇',
      chi = '𝜒',
    },
    lsp = lsp,
    markdown = {
      MarkdownH1 = '󰉫 ', -- Used by builtin markdown source
      MarkdownH2 = '󰉬 ',
      MarkdownH3 = '󰉭 ',
      MarkdownH4 = '󰉮 ',
      MarkdownH5 = '󰉯 ',
      MarkdownH6 = '󰉰 ',
    },
    menu = {
      actions = {
        outline = {
          left = '󰨂',
          right = '󰨃',
          up = '󰚷',
          down = '󰚶',
          swap = '󰩥',
          filter = '󱃦',
        },
        filled = {
          up = '󰍠',
          down = '󰍝',
          left = '󰍞',
          right = '󰍟',
          swap = '󰩤',
          filter = '󱃥 ',
        },
      },
      hamburger = '󰍜 ',
      hamburger_open = '󰮫 ',
    },
    misc = {
      ai = '󱚦 ',
      actions = ' ',
      arrow_right = '',
      block = '▌',
      bookmark = ' ',
      bug = ' ', --  '󰠭'
      calendar = ' ',
      caret_right = '',
      check = '󰄬 ',
      chevron_right = ' ',
      circle = ' ',
      circle_filled = ' ',
      circle_filled_large = '⬤',
      circle_slash = ' ',
      clock = ' ',
      code = ' ',
      comment = '󰅺 ',
      dashboard = ' ',
      datetime = '󱛡 ',
      double_chevron_right = '»',
      down = '⇣',
      ellipse_dbl = '',
      ellipsis = '…',
      exit = '󰗼 ',
      fire = ' ',
      gear = ' ',
      git = ' ',
      github = '󰊤 ',
      history = '󰄉 ',
      hook = '󰛢',
      hook_disabled = '󰛣 ',
      indent = 'Ξ',
      kebab = '',
      lightbulb = '󰌶 ',
      line = '', -- 'ℓ'
      list = ' ',
      lock = '',
      modified = '●',
      newline = '',
      note = '󰎞 ',
      package = ' ',
      pencil = ' ', -- '󰏫',
      plus = ' ',
      project = ' ',
      question = ' ',
      quickfix = '󱡠',
      robot = '󰚩 ',
      search = '󰍉 ',
      shaded_lock = ' ',
      sign_in = ' ',
      surround = '󰗅 ',
      tab = '⇥',
      table = ' ',
      tools = ' ',
      up = '⇡',
    },
    numbers = {
      boxed = { '󰎦', '󰎩', '󰎬', '󰎮', '󰎰', '󰎵', '󰎸', '󰎻', '󰎾' },
      boxed_filled = { '󰎤', '󰎧', '󰎪', '󰎭', '󰎱', '󰎳', '󰎶', '󰎹', '󰎼', '󰽽' },
      circled = { '①', '②', '③', '④', '⑤', '⑥', '⑦', '⑧', '⑨', '⑩', '⑪', '⑫' },
      circled_filled = { '󰲠', '󰲢', '󰲤', '󰲦', '󰲨', '󰲪', '󰲬', '󰲮', '󰲰' },
      dice = { '⚀', '⚁', '⚂', '⚃', '⚄', '⚅' },
      roman = { '|', 'Ⅱ', 'Ⅲ', 'Ⅳ', 'Ⅴ', 'Ⅵ', 'Ⅶ', 'Ⅷ', 'Ⅸ', 'Ⅹ', 'Ⅺ', 'Ⅻ' },
      arabic = { '󰬺', '󰬻', '󰬼', '󰬽', '󰬾', '󰬿', '󰭀', '󰭁', '󰭂' },
      header = { '󰉫', '󰉬', '󰉭', '󰉮', '󰉯', '󰉰' },
    },
    separators = {
      angle_quote = {
        left = '«',
        right = '»',
      },
      chevron = {
        left = '',
        right = '',
        down = '',
      },
      circle = {
        left = '',
        right = '',
      },
      arrow = {
        left = '',
        right = '',
      },
      slant = {
        left = '',
        right = '',
      },
      bar = {
        left = '⎸',
        right = '⎹',
      },
      bar2 = {
        vertical_block = '█',
        vertical_center = '┃',
        vertical_center_thin = '│',
        vertical_left_thick = '▌',
        vertical_left = '▎',
        vertical_left_thin = '▏',
        vertical_right = '▎',
        vertical_right_thin = '▕',
        vertical_right_thick = '▐',
        upper_right_corner = '┓',
        upper_right_corner_thin = '┐',
        upper_left_corner = '┏',
        upper_left_corner_thin = '┌',
        lower_left_corner = '┗',
        lower_left_corner_thin = '└',
        lower_right_corner = '┛',
        horizontal = '━',
        horizontal_thin = '─',
        lower_horizontal = '▁',
        lower_horizontal_thin = '_',
        lower_horizontal_thick = '▄', -- lower half block (unicode)
        lower_right_corner_thick = '▟',
        lower_left_corner_thick = '▙',
        upper_horizontal_thick = '▀',
        upper_right_corner_thick = '▜',
        upper_left_corner_thick = '▛',
      },
    },
  },

  -- Various buffer and file types that should be ignored.
  ignored = {
    buffer_types = {
      'gitcommit',
      'health',
      'help',
      'nofile',
      'quickfix',
      'terminal',
      'trouble',
    },
    file_types = {
      '',
      'bigfile',
      'checkhealth',
      'crates.nvim',
      'git',
      'gitrebase',
      'health',
      'help',
      'lazy',
      'log',
      'noice',
      'notify',
      'oil',
      'qf',
      'snacks_dashboard',
      'snacks_input',
      'snacks_notif',
      'snacks_picker_input',
      'snacks_win',
      'trouble',
      'vim',
    },
    lsp = {
      'copilot',
      'harper-ls',
    },
    paths = {
      '~/.cache',
      '~/.cargo',
      '~/.local/state',
      '~/.rustup',
      tostring(vim.fn.stdpath('data')),
      tostring(vim.fn.stdpath('state')),
    },
    progress = {
      'basedpyright',
      'copilot',
    },
  },

  statusline = {
    modes = {
      ['n'] = 'N',
      ['no'] = 'N',
      ['nov'] = 'N',
      ['noV'] = 'N',
      ['no'] = 'N',
      ['niI'] = 'N',
      ['niR'] = 'N',
      ['niV'] = 'N',
      ['v'] = 'V',
      ['V'] = 'V',
      [''] = 'V',
      ['s'] = 'S',
      ['S'] = 'S',
      [''] = 'S',
      ['i'] = 'I',
      ['ic'] = 'I',
      ['ix'] = 'I',
      ['R'] = 'R',
      ['Rc'] = 'R',
      ['Rv'] = 'R',
      ['Rx'] = 'R',
      ['r'] = 'R',
      ['rm'] = 'R',
      ['r?'] = 'R',
      ['c'] = 'C',
      ['cv'] = 'C',
      ['ce'] = 'C',
      ['!'] = 'T',
      ['t'] = 'T',
      ['nt'] = 'T',
    },

    wordcount = {
      markdown = true,
      text = true,
      vimwiki = true,
    },
  },

  ui = {
    border = {
      name = 'single',
      chars = { '─', '│', '─', '│', '┌', '┐', '┘', '└' },
    },
    float = {
      border = 'single',
      relative = 'editor',
      style = 'minimal',
      height = 0.75,
      width = 0.8,
      wo = { wrap = true },
    },
  },
}

return M

-- local completion_kinds = {
--         Array = " ",
--         Boolean = " ",
--         Class = "󰠱 ",
--         Color = " ",
--         Constant = " ",
--         Constructor = " ",
--         Enum = "練",
--         EnumMember = " ",
--         Event = " ",
--         Field = "",
--         File = " ",
--         Folder = " ",
--         Function = "󰊕",
--         Image = "󰈫",
--         Interface = " ",
--         Keyword = "󰌋",
--         Method = "󰆧",
--         Module = " ",
--         Operator = " ",
--         Property = "󰜢 ",
--         Reference = " ",
--         Snippet = "",
--         Struct = "",
--         Text = " ",
--         TypeParameter = " ",
--         Unit = " ",
--         Value = " ",
--         Variable = " ",
--     }
-- icons = {
--         diagnostics = {
--             error = "",
--             warn = "",
--             hint = "",
--             info = "",
--         },
--         folders = {
--             AppData = "󰉌",
--             Public = "󱧰",
--             bin = "󱧺",
--             colors = "󱁽",
--             dev = "󱧼",
--             doc = "󱂷",
--             docs = "󱂷",
--             lua = "󰉋",
--             closed = "",
--             open = "",
--             empty = "",
--             empty_open = "",
--             symlink = "",
--             [".git"] = "",
--             [".github"] = "",
--             [".cache"] = "󰪺",
--             [".vim"] = "󰉋",
--         },
--         files = {
--             default = "",
--             no_extension = "",
--             license = "",
--             news = "󰎕",
--             readme = "",
--             code_of_conduct = "󱃱",
--             todo = "󰝖",
--             [".bashrc"] = "󰒓",
--             extensions = {
--                 asm = "",
--                 astro = "",
--                 angular = "󰚿",
--                 basic = "󰫯",
--                 c = "",
--                 cpp = "󰙲",
--                 el = "",
--                 html = "",
--                 js = "",
--                 json = "",
--                 css = "",
--                 md = "󰽛",
--                 norg = "",
--                 py = "",
--                 ts = "",
--                 java = "",
--                 lua = "",
--                 rb = "",
--                 go = "󰟓",
--                 gd = "",
--                 git = "",
--                 rs = "",
--                 php = "",
--                 sh = "",
--                 txt = "",
--                 hs = "",
--                 lisp = "",
--                 scm = "",
--                 tailwind = "󱏿",
--                 svelte = "",
--                 jsx = "",
--                 mod = "",
--                 sum = "",
--                 org = "",
--                 db = "",
--                 sqlite = "",
--                 groovy = "",
--                 gradle = "",
--                 maven = "",
--                 vue = "",
--                 vim = "",
--                 yaml = "",
--                 zig = "",
--                 ["7z"] = "󰗄",
--                 gz = "󰗄",
--                 tar = "󰗄",
--                 rar = "󰗄",
--                 tgz = "󰗄",
--                 xz = "󰗄",
--                 z = "󰗄",
--                 zip = "󰗄",
--                 webm = "󰈫",
--                 mp4 = "󰈫",
--                 mkv = "󰈫",
--                 mp3 = "󰈣",
--                 gif = "󰵸",
--                 jpeg = "󰈥",
--                 jpg = "󰈥",
--                 png = "󰸭",
--                 webp = "󰈟",
--             },
--         },
--     }
