# What protocol to use when performing git operations. Supported values: ssh, https
git_protocol: https
# What editor gh should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor: ~/Dev/eo_contrib/neovim/bin/nvim
# Aliases allow you to create nicknames for gh commands
aliases:
  co: pr checkout
# pager: bat --paging=auto --theme="Sublime Snazzy"
pager: delta
version: "1"
