-- local M = {}
--
-- function M.luapad(x)
--   require('Luapad.run').run(x)
-- end
--
-- M.luapad(print 'hell' )
-- return M

-- x = {}
--
-- local function setup()
--   require('swenv').setup({
--     get_venvs = function(venvs_path)
--       return require('swenv.api').get_venvs(venvs_path)
--     end,
--     venvs_path = vim.fn.expand(
--       {
--         { "jupyterlab" == "~/.local/pipx/venvs/jupyterlab" },
--         { "ptpython"  == "~/.local/pipx/venvs/ptpython" },
--       }
--     ),
--   })
-- end
--
-- ---@param x string[]
-- local function virtualenvs(x)
--   require("swenv.api").get_current_venv(x)
--   return x
-- end
--
-- print({setup(), virtualenvs(x)})
