#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "Snazzy"
    # colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "slant"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true 
    filemanager = 'defx'
    filetree_direction = 'left'
    relativenumber = true
    autocomplete_method = 'coc'
    enable_ycm = false
    enable_debug = true
    enable_googlesuggest = false
    enable_key_frequency = true
    guifont = "Fira Code:h13"
    default_indent = 2
    automatic_update = true
#   bootstrap_before = "myspacevim#before"
#   boostrap_after = "myspacevim#after"
    disabled_plugins = ["neomake/neomake", "psf/black"] 
    vimcompatible = true
    enable_os_fileformat_icon = true

[[custom_plugins]]
  name = "neovimhaskell/haskell-vim"
  merged = 0

[[custom_plugins]]
  name = "dmix/elvish.vim" 
  merged = 0

[[custom_plugins]]
  name = "yuki-ycino/fzf-preview.vim"
  merged = 0

[[custom_plugins]]
  name = 'psf/black' 
  merged = 1

[[custom_plugins]]
  name = 'numirias/semshi'
  merged = 0

[[custom_plugins]]
  name = 'frazrepo/vim-rainbow' 
  merged = 0

[[custom_plugins]]
  name = 'connorholyday/vim-snazzy'
  merged = 0

[[layers]] 
  name = 'VersionControl'
  enable = true

[[layers]]
  name = 'core#statusline'
  enable = false

[[layers]]
  name = 'core#tabline'
  enable = false

[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "smart"

[[layers]]
  name = 'shell'
  default_position = 'bottom'
  default_height = 40

[[layers]]
  name = "gtags"
  enable = true
  gtagslabel = "pygments"

[[layers]]
  name = "checkers"
  enable = true

[[layers]]
  name = "github"
  enable = true

[[layers]]
  name = "lang#python"
  enable = true
  
[[layers]]
  name = "lang#julia"
  enable = true

[[layers]]
  name = "lang#haskell"
  enable = true

[[layers]]
  name = "lang#c"
  enable_clang_syntax_highlight = true
  enable = true

[[layers]]
  name = "lang#go"
  enable = true

[[layers]]
  name = "lang#markdown"
  enable = true

[[layers]]
  name = "lang#rust"
  enable = true
  
[[layers]]
  name = "lang#sh"
  enable = true
  
[[layers]]
  name = "lang#javascript"
  enable = true

[[layers]]
  name = "lang#typescript"
  enable = true


[[layers]]
  name = "lang#toml"
  enable = true

[[layes]]
  name = "fzf"
  enable = true

#[[layers]]
#  name = "denite"
#  enable = true

[[layers]]
  name = 'edit'
  enable = true

[[layers]]
  name = 'git'
  enable = true

[[layers]]  
  name = 'cscope'
  enable = true

[[layers]]
  name = 'colorscheme' 
  
[[layers]]
  name = 'incsearch'

[[layers]]
  name = 'lang#vim'
  enable = true

[[layers]]
  name = "lsp"
  enable = true
  filetypes = [
    "rust",
    "python",
    "javascript",
    "typescript",
    "haskell",
    "go",
    "julia",
    "sh",
  ]
  [layers.override_cmd]
    rust = ['rls']
    python = ['pyls']
    javascript = ['javascript-typescript-stdio']
    typescript = ['typescript-language-server', 'start']
    haskell = ['hie-wrapper', '--lsp']
    julia = ['julia', '--startup-file=no', '--history-file=no', '-e', 'using LanguageServer; server = LanguageServer.LanguageServerInstance(STDIN, STDOUT, false); server.runlinter = true; run(server);']
    go = ['gopls']
    sh = ['bash-language-server', 'start']
