return {
  {
    'folke/tokyonight.nvim',
    lazy = false,
    priority = 1003,
    opts = {
      style = 'storm',
      transparent = false,
      terminal_colors = true,
      styles = {
        comments = { italic = true },
        keywords = { italic = true },
        functions = { italic = true, bold = true },
        variables = { italic = true },
        sidebars = 'transparent', -- dark, transparent, normal
        floats = 'transparent',
      },
      sidebars = { 'qf', 'help', 'fzf_lua', 'overseer', 'terminal' },
      lualine_bold = true, -- when true, section headers in lualine will be bold
    },
    config = function(_, opts)
      local tokyonight = require('tokyonight')
      tokyonight.setup(opts)
      tokyonight.load()
    end,
  },
  {
    'catppuccin/nvim',
    priority = 1003,
    lazy = false,
    name = 'catppuccin',
    opts = {
      flavor = 'mocchiato',
      transparent_background = false,
      term_colors = true,
      compile = { enabled = true, path = vim.fn.stdpath('cache') .. '/catppuccin', suffix = '_compiled' },
      styles = {
        comments = { 'italic' },
        conditionals = { 'italic' },
        loops = { 'italic' },
        functions = { 'italic', 'bold' },
        keywords = { 'italic' },
        variables = { 'italic' },
        strings = {},
        numbers = {},
        booleans = { 'italic', 'bold' },
        properties = {},
        types = {},
        operators = {},
      },
      default_integrations = true,
      integrations = {
        native_lsp = {
          enabled = true,
          virtual_text = {
            errors = { 'italic' },
            hints = { 'italic' },
            warnings = { 'italic' },
            information = { 'italic' },
            ok = { 'italic' },
          },
          underlines = {
            errors = { 'undercurl' },
            hints = { 'underline' },
            warnings = { 'undercurl' },
            information = { 'underline' },
            ok = { 'underline' },
          },
          inlay_hints = { background = true },
        },
        alpha = true,
        barbecue = {
          dim_dirname = true,
          bold_basename = true,
          dim_context = true,
          alt_background = true,
        },
        beacon = false,
        -- blink_cmp = true,
        -- git_graph = true,
        -- colorful_winsep = {
        --   enabled = true,
        --   -- color = 'red',
        -- },
        cmp = true,
        dadbod_ui = true,
        dap = true,
        dap_ui = true,
        diffview = true,
        dropbar = {
          enabled = false,
          color_mode = false,
        },
        fidget = true,
        fzf = true, -- fzf-lua
        gitsigns = true,
        gitgutter = true,
        grug_far = true,
        headlines = true,
        illuminate = { enabled = true, lsp = false },
        indent_blankline = {
          enabled = true,
          -- scope_color = "",
          colored_indent_levels = false,
        },
        leap = true,
        lsp_trouble = true,
        markdown = true,
        mason = true,
        mini = false,
        navic = {
          enabled = false,
          custom_bg = 'NONE',
        },
        neogit = true,
        neotest = true,
        noice = true,
        neotree = true,
        notify = true,
        render_markdown = true,
        sandwhich = false,
        semantic_tokens = true,
        -- snacks = true,
        nvim_surround = true,
        telescope = { enabled = true },
        treesitter_context = true,
        treesitter = true,
        ts_rainbow = true,
        ts_rainbow2 = false,
        octo = true,
        overseer = true,
        rainbow_delimiters = true,
        window_picker = true,
        which_key = true,
        vim_sneak = false,
      },
    },
  },
  -- { 'rebelot/kanagawa.nvim', lazy = false, name = 'kanagawa' },
  -- {
  --   'ellisonleao/gruvbox.nvim',
  --   name = 'gruvbox',
  --   lazy = false,
  --   config = function() require('gruvbox').setup() end,
  -- },
}
