return {
  { 'norg' },
  { 'quarto' },
  -- { 'itchyny/calendar.vim', cmd = { 'Calendar' } },
  -- { 'folke/zen-mode.nvim', opts = {}, cmd = { 'ZenMode' } },
  { 'dhruvasagar/vim-table-mode', ft = { 'markdown', 'norg' } },
  --  `MDRun` with Inlyne works well for now
  -- {
  --   'iamcco/markdown-preview.nvim',
  --   build = function() fn['mkdp#util#install']() end,
  --   ft = { 'markdown' },
  --   config = function()
  --     vim.g.mkdp_auto_start = 0
  --     vim.g.mkdp_auto_close = 1
  --   end,
  -- },
  -- {
  --   'jbyuki/nabla.nvim',
  --   ft = { 'markdown', 'norg', 'org', 'rst', 'latex', 'quarto' },
  --   enabled = false,
  --   config = function() require('nabla').enable_virt() end,
  --   -- opts = {},
  --   keys = {
  --     { '<localleader>nn', function() require('nabla').popup() end, desc = 'Notation' },
  --   },
  -- },
  -- {
  --   'vim-pandoc/vim-pandoc',
  --   ft = 'markdown',
  --   event = 'VeryLazy',
  --   enabled = false,
  --   dependencies = { 'vim-pandoc/vim-pandoc-syntax' },
  -- },
  -- {
  --   'frabjous/knap',
  --   enabled = false,
  --   ft = { 'markdown', 'latex' },
  --   keys = {
  --     { '<localleader>np', function() require('knap').process_once() end, desc = 'Preview' },
  --     { '<localleader>nc', function() require('knap').close_viewer() end, desc = 'Close Preview' },
  --     { '<localleader>nt', function() require('knap').close_viewer() end, desc = 'Toggle Preview' },
  --     { '<localleader>nj', function() require('knap').forward_jump() end, desc = 'Forward jump' },
  --   },
  -- },
}
-- build = function()
--   local icanhazmajjjik = pcall(require, 'magick')
--   local is_macsaucy = function() return string.format(_G.os) end
--   -- if vim.uv.os_uname().sysname['Darwin'] == 1 then return end
--   -- local macsaucy = g.os
--   if not icanhazmajjjik and vim.fn.executable('luarocks') == 1 then
--     if is_macsaucy then
--       vim.fn.system('luarocks --lua-dir=$(brew --prefix)/opt/lua@5.1 --lua-version=5.1 install magick')
--     else
--       vim.fn.system('luarocks --local --lua-version=5.1 install magick')
--     end
--     if vim.v.shell_error ~= 0 then vim.notify('Error installing magick with luarocks', vim.log.levels.WARN) end
--   end
-- end,
-- config = function(_, opts)
--   local has_magick = pcall(require, 'magick')
--   if has_magick then require('image').setup(opts) end
-- end,
